version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.4.0
jobs:
  generate_config:
    executor: continuation/default
    steps:
      - checkout
      - run:
          name: Install OpenJDK 17
          command: |
            sudo apt-get update && sudo apt-get install openjdk-17-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
            java -version
      - run:
          name: generate build configuration
          command: |
            sudo chmod +x gradlew
            ./gradlew generateModuleTestConfig
      - continuation/continue:
          configuration_path: .circleci/generated_config.yml
workflows:
  generate_configuration:
    jobs:
      - generate_config