# This is the template for the CircleCI configuration that the `generateModuleTestsConfig`
# Gradle task will use to generate the build configuration for our modules.

version: 2.1

jobs:
  # Job for building, testing and checking Gradle modules
  build_test_check:
    docker:
      -image: cimg/android:2023.05
    resource-class: << parameter.resourceClass >>
    parameters:
      moduleName:
        type: string
      gradleTask:
        type: string
      resourceClass:
        type: string
      dependencyCacheKey:
        type: string
      steps:
        - checkout
        - restore_cache:
            key: << parameters.dependencyCacheKey >>
        - run:
            name: Build, test, check (<< parameters.moduleName >>)
            command: |
              ./gradlew << parameters.gradleTask >>

        - save_cache:
            key: << parameters.dependencyCacheKey >>
            paths:
              - ~/.gradle/caches
workflows:
  build-test-check:
    jobs:

